### ISSUE TITLE
Feature request: Delimiters besides WSpace

### ISSUE THREAD

**Issue by JoePython1** [bitfield/script#100]
For the Column function, can we specify alternate delimiters besides white space?

**Comment by bitfield** [comment]
Hey @JoePython1! That sounds like a good idea. Can you outline a potential use case for this? For example, what program's output might you want to filter that uses non-whitespace delimiters, and why? This will help us think about what a good API for the feature might look like.

**Comment by JoePython1** [comment]
Let say you want to parse the /etc/passwd file for example a get a user's home directory. With a Perl one liner I  would use the 'F' option to switch the default delimiter to something else. I am not sure how the golang API would like though.

```
$ perl -F: -lane 'print $F[-2] if /^root/' /etc/passwd
/root
```

**Comment by bitfield** [comment]
Excellent! Why don't you have a go at writing the same thing using `script`, with `Column`, and see how it would make sense to supply the delimiter characters.

**Comment by bitfield** [comment]
Closing for now, but let's reopen once we have a demo of the suggested new Column API.
