### ISSUE TITLE
How do I simply exit after `Exec` without using anything else

### ISSUE THREAD

**Issue by rew1nter** [bitfield/script#104]
`Close`, `ExitStatus`, `Wait` after exec don't execute the command. Is there any other way to simply check the error and exit after execution but using smth like `String`/`Stdout` ?

**Comment by bitfield** [comment]
Can you post the code you're using @rew1nter?

**Comment by rew1nter** [comment]
### What i'm having to do
Since I don't need the stdout or output of the ` xprogram ` i'm executing, I only care about the error. I just need to be assured that the program was executed successfully.
```
_, err := script.Exec("xprogram -f -f ").String()
	if err != nil {
		log.Fatal("Broke while executing xprogram: ", err)
	}
```

### What I'd like to do
Aforementioned, I only need to know if the program executed successfully. So I would want smth like this where the program will exit after execution:
```
err := script.Exec("xprogram -f -f ")
	if err != nil {
		log.Fatal("Broke while executing xprogram: ", err)
	}
```


Please point me to doc if you already have smth like this that I missed

**Comment by bitfield** [comment]
I think your first example is absolutely fine! If you don't need the output, by all means ignore it—there doesn't seem much value in providing a duplicate API method that only returns `error`.

**Comment by rew1nter** [comment]
Aight. Thanks for fast response.

**Comment by rew1nter** [comment]
Reopening cause thought I should let you know this.

> I think your first example is absolutely fine! If you don't need the output, by all means ignore it—there doesn't seem much value in providing a duplicate API method that only returns `error`.

Consider this use case, You're executing `xprogram`, in goroutines with different flag values as necessary, that has a large output. The output of `xprogram` is taking 2 seconds at average to be read into a string. Now if you're executing 60 goroutines with a limited waitgroup, that's 60X2=2 minutes of more time you would have to wait. 

This is a very common scenario for me at least.
So it wouldn't be completely useless to add a similar API. Wanted to let you know this just. You can close this issue.
