### ISSUE TITLE
Add (optional) timeout argument to `Wait()`

### ISSUE THREAD

**Issue by rew1nter** [bitfield/script#105]
A timeout feature would be helpful for a program that is taking too long or stuck during execution.

**Comment by rew1nter** [comment]
### Extra
A way of accessing the timeout. so I can perform *Ytask* when `Xprogram` is stuck for 3 minutes (where timeout for Xprgrm is set to 4 minutes).

**Comment by bitfield** [comment]
But if a command gets stuck, or hasn't finished within a reasonable time, is it still useful to continue and use the data it's produced?

Maybe an alternative idea that's worth considering is adding a timeout argument to `Wait`—in other words, instead of just waiting forever, wait for a specified time and then consider the command failed.

**Comment by rew1nter** [comment]
> ### Extra
> A way of accessing the timeout. so I can perform _Ytask_ when `Xprogram` is stuck for 3 minutes (where timeout for `Xprogram` is set to 4 minutes).

I didn't mean using any data from `Xprogram`. Meant executing `anotherprogram` or `func` when `Xprogram` is already stuck for 3 minutes where the `Xprogram` will exit after 4 minutes because of timeout. 

### Example
Here I'm expecting a successful execution of `Xprogram` to be finished within 2 minutes (*timeout set to 4 minutes*). But if it's taking more than 2 minutes, I want to already start doing smth before the timeout (`Yprogram` at 3 minutes I.e) rather than just waiting the full time period doing nothing. Then after 4 minutes I can check the partial output provided by the `Xprogram`

**Comment by rew1nter** [comment]
> But if a command gets stuck, or hasn't finished within a reasonable time, is it still useful to continue and use the data it's produced?
> 
> Maybe an alternative idea that's worth considering is adding a timeout argument to 

> But if a command gets stuck, or hasn't finished within a reasonable time, is it still useful to continue and use the data it's produced?
> 
> Maybe an alternative idea that's worth considering is adding a timeout argument to `Wait`—in other words, instead of just waiting forever, wait for a specified time and then consider the command failed.

 Isnt the wait arguement you're talking about what `Timeout()` is supposed to do by default?

`Timeout(3 * time.Second)` should wait for 3 seconds and then consider it dead.

**Comment by bitfield** [comment]
> I didn't mean using any data from Xprogram. Meant executing anotherprogram or func when Xprogram is already stuck for 3 minutes where the Xprogram will exit after 4 minutes because of timeout.

I'm having some trouble understanding what you mean here. Could you help me out by writing some code that you'd like to be able to write, and explain what its effect would be?

> Isnt the wait arguement you're talking about what Timeout() is supposed to do by default?

Yes, exactly. I'm saying in that case we don't need to add a new method—Wait already does what we want, we just need to add a timeout argument (the default timeout being forever). Or perhaps I've misunderstood what you meant?

**Comment by rew1nter** [comment]
> Yes, exactly. I'm saying in that case we don't need to add a new method—Wait already does what we want, we just need to add a timeout argument (the default timeout being forever). 

Yep. That's it then. 
Add some examples with close(), wait() and such other funcs in the repo tho.

> I'm having some trouble understanding what you mean here. Could you help me out by writing some code that you'd like to be able to write, and explain what its effect would be?

I'm afraid not. 
aforementioned it's an extra feature request. You can just ignore it

**Comment by bitfield** [comment]
It's a great feature suggestion, but if there are no useful programs that use it, then adding it would complicate the library with no compensatory benefit. (Don't feel bad, because this is true of almost other every feature suggestion, too.)
