### ISSUE TITLE
Make `AppendFile()` return the newly appended lines as `[]string`

### ISSUE THREAD

**Issue by rew1nter** [bitfield/script#107]
This would be very useful if I could check what's being appended within my code.

**Comment by bitfield** [comment]
Can you think of an example where this would be useful?

**Comment by rew1nter** [comment]
reading output of Exec("X program") while getting the job of appending it to a file at the same time

**Comment by bitfield** [comment]
There have been suggestions before for something like `Tee()` that splits the pipe into two identical streams, which would sort of achieve what you want, wouldn't it? Unfortunately, we haven't really come up with a nice API for it yet.

**Comment by rew1nter** [comment]
> There have been suggestions before for something like Tee() that splits the pipe into two identical streams, which would sort of achieve what you want, wouldn't it?
absolutely.

**Comment by No-one-important** [comment]
would something like Tee() return the second stream to be used separately or be something that takes a pointer to the variable to write to or would you give Tee() the actions to apply to the pipe.

**Comment by bitfield** [comment]
Right now `AppendFile` returns `n, err`, and I can't see a way to change that without breaking existing code, so closing with regret.
