### ISSUE TITLE
Add feature to execute command in the specified directory 

### ISSUE THREAD

**Issue by rew1nter** [bitfield/script#109]
There are some bins that are put in a directory with lot of config files and other directories which are needed during execution so it's easier to execute the command on that directory rather than soft linking them all. I.e
Some java jars I've dealt with are like this. 

Std `os/exec` has this `cmd.Dir()` function for exactly this job.

**Comment by bitfield** [comment]
Great suggestion! Well, you know the drill by now: let's try to write an example program that solves a real-world problem and requires this feature.

**Comment by bitfield** [comment]
Closing as for #112.
