### ISSUE TITLE
Is it possible...

### ISSUE THREAD

**Issue by rmasci** [bitfield/script#111]
I wrote a program that uses script to do a dump of mysql databases. Mainly because I can encrypt the passwords in a config file, and nobody can see how I encrypt / decrypt them because it's compiled.  What I want to do is add a restore function. What I need to do, I can open the shell using script, but is it possible when it reads, "mysql>" to send "source <mysqlbackupfile.sql>" ?

**Comment by rmasci** [comment]
Even from the command line when I ran '/bin/cat file.sql | /usr/bin/mysql' didn't work, but if I entered mysql shell, and ran 'source file.sql' it did.   I changed the way my dumps are created and now using a pipe works. So my files are gzipped when I create them, the restore procedure does: 'script.Exec("zcat "+ file.sql).Exec("/usr/bin/mysql").Stdout()' -- that works great. (Thank you!)

Now what I am wondering is if it's possible to insert a FilterLine in between the two. I'd like to create some kind of progress meter. Problem is when I do this I only get about 50 lines before it quits. I think its because FilterLine is run in a goroutine. Any idea how a progress meter could be implemented?

**Comment by bitfield** [comment]
> I only get about 50 lines before it quits

That sounds like a bug—let me look into that and get back to you.

A progress meter is a nice idea, if we had a way to predict (or at least guess at) how many lines there are in total.

**Comment by rmasci** [comment]
I found that after line 50 there is a very long line that is 1.7mb -- that's where it stops.

**Comment by rmasci** [comment]
What I found is that if I change the script.FilterScan to include the block size  it works fine with input that has long lines.
`	return p.Filter(func(r io.Reader, w io.Writer) error {
		scanner := bufio.NewScanner(r)
		buf := make([]byte, <byte size> )
		scanner.Buffer(buf, <byte size>)`

I'd make this a configuration, and I tried adding it to the Pipe struct.  So that you'd call
pipe:=script.NewPipe()
pipe.Blocksize="10M"

That didn't seem to work for me tho. What would be a good way to add a 'blocksize' in as a configurable thing? Maybe:
script.Exec("zcat mysql.sql.gz").BlockSize("10mb").Exec("mysql -u user -p<password> database").Stdout ??

**Comment by rmasci** [comment]
> Please be aware that this is not a sufficient approach to security. It's called [Security Through Obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity) and could even be considered an antipattern. Your compiled binary can be reverse-engineered to extract secrets and determine how you encrypt your files.

Absolutely!!! The longer story is that the passwords are encrypted, stored in a config file, but unlike a python script, you can't read the binary to extract how the password was encrypted.  Well you can but it's a LOT more difficult to reverse-engineer. Even then I put a few tricks into the salt of the encrypted string that obfuscate and so that the config file can't be used across other systems.  
```
~$ sqlrun --help 2>&1 | grep conf
  -c, --conf string                             Sqlrun Configuration File (default "/etc/sqlrun/sqlrun.conf")
```

**Comment by bitfield** [comment]
I'm happy that OP's problem appears to be resolved, so closing, with thanks for the suggestion.
