### ISSUE TITLE
Add SHA-512 Hashing Sink

### ISSUE THREAD

**Issue by terrorbyte** [bitfield/script#113]
# Use Case

Currently SHA-256 is the only supported hashing algorithm (and there is some engineering design decisions in #39), this PR creates a SHA-512 sink that works identically the the current SHA-256 design but just with the `crypto/sha512` library imported and the same functions applied.

## Tests

As per the contributor guidelines I ran also created all the tests and test data. Here is the following output:

```console
$ go test -v | grep -i sha512
=== RUN   TestSHA512Sums_OutputsCorrectHashForEachSpecifiedFile
=== PAUSE TestSHA512Sums_OutputsCorrectHashForEachSpecifiedFile
=== RUN   TestSHA512Sum_OutputsCorrectHash
=== PAUSE TestSHA512Sum_OutputsCorrectHash
=== CONT  TestSHA512Sum_OutputsCorrectHash
=== RUN   TestSHA512Sum_OutputsCorrectHash/for_no_data
=== RUN   TestSHA512Sum_OutputsCorrectHash/for_short_string
=== RUN   TestSHA512Sum_OutputsCorrectHash/for_string_containing_newline
--- PASS: TestSHA512Sum_OutputsCorrectHash (0.00s)
    --- PASS: TestSHA512Sum_OutputsCorrectHash/for_no_data (0.00s)
    --- PASS: TestSHA512Sum_OutputsCorrectHash/for_short_string (0.00s)
    --- PASS: TestSHA512Sum_OutputsCorrectHash/for_string_containing_newline (0.00s)
=== CONT  TestSHA512Sums_OutputsCorrectHashForEachSpecifiedFile
--- PASS: TestSHA512Sums_OutputsCorrectHashForEachSpecifiedFile (0.00s)
=== RUN   ExamplePipe_SHA512Sum
--- PASS: ExamplePipe_SHA512Sum (0.00s)
=== RUN   ExamplePipe_SHA512Sums
--- PASS: ExamplePipe_SHA512Sums (0.00s)
```

One note, in the original patchset I added a `testdata/sha512Sum.input.txt` file that has the same content as `testdata/sha256Sum.input.txt`. This was to meet the contribution guidelines, but I think that it could be beneficial to generalize the test data to work with arbitrary hashing functions (ie something like `testdata/hashSum.input.txt`).

## Documentation

I updated the docs as well to match the SHA-256 functions. I am happy to add some more README examples for both the functions if need be.

**Comment by terrorbyte** [comment]
Opened PR as #114

**Comment by bitfield** [comment]
Thanks @terrorbyte! This looks very good.

One thing I don't see here, despite your heading, is a use case. Is there some real-world user problem that needs to be solved specifically using SHA-512 hashing, rather than just "some arbitrary reasonably secure hash"? If so, we can mention it in the documentation and explain when to use this.

**Comment by bitfield** [comment]
That's great—could you give an example of the kind of program that you'd like to write with `script` that needs a SHA-512 hash?

It strikes me that perhaps it would be most flexible to simply provide a `Hash` method, that defaults to SHA-256 (as perhaps the best trade-off between speed and security, for now), but can take an optional `hash.Hasher` as argument. So:

```go
script.Echo("data").Hash().Stdout()
```

but also:

```go
script.Echo("secret password").Hash(sha512.New()).Stdout()
```

**Comment by terrorbyte** [comment]
As for the API design part, I am of two minds in this regard. 

First, I do foresee it becoming pretty common place to utilize other generic hashing algorithms and utilizing the generic `Hash` with `hash.Hasher` might be more flexible in real life situations, for example I have a private fork that hash support for sha1, md5, sha384, md4, and some other lesser known algorithms that I use in real life due to my offensive security work but are not "preferable" to expose to users for safety reasons, but it would have been very nice to be able to just throw a `hash.Hasher` type at this instead of building tests and calls for each. The issue with this comes up when you start getting to some more of the modern hashing algorithm choices such as `bcrypt` (https://pkg.go.dev/golang.org/x/crypto@v0.0.0-20220411220226-7b82a4e95df4/bcrypt) or `scrypt` (https://pkg.go.dev/golang.org/x/crypto@v0.0.0-20220411220226-7b82a4e95df4/scrypt), which utilize tunable options and do not return a `hash.Hasher` type. That also being said, I don't expect these will ever hit stdlib and will be relegated to `x/crypto` so might be considered to be "non-goals" fitting the stdlib usage requirements.

Second, I don't think having a "default" hash actually makes logical sense in the context of hashing algorithms, because you are rarely using them in optionally and are explicitly dictated which ones to use. For example I'm given specific hashes for checksums and applying the concept of "hashing" to it could mean many different things. If anything, it might be a bit more cumbersome, but the algorithm structure used now might be in line with real use case vs the proposed "optional argument". I'd rather see `${ARBITRARY_ALGORITHM}Sum()` or `Hash(${ARBITRARY_ALGORITHM}.New())` than making assumptions that could have security impact.

**Comment by No-one-important** [comment]
While sha-256 is considered secure unless data is salted most passwords can be cracked easily using online tools such as [dcode.fr](https://www.dcode.fr/sha256-hash)

**Comment by terrorbyte** [comment]
No one indicated using any of these for password hashes, and if they do they are not reading modern guidance from the last 20 years. Hashing algorithms are used in many more places than just password hashes, please take a moment to read my examples.

For the record, I build password cracking machines and regularly compete in competitions. From a cracking perspective there is only fractional differences between SHA-256 and SHA-512 algorithms cracking speeds in the real world. If you are using any SHA algorithm for password storage without many rounds, salt, and cost factors you are doing something horribly wrong. Modern `crypt(3)` fully deprecates SHA-512 and SHA-256 even with 5000 rounds for a reason, and I don't for see people using thousands of pipes of `.SHA512Sum()`

**Comment by mahadzaryab1** [comment]
@bitfield What's the status of this? Can I pick it up?

**Comment by bitfield** [comment]
Sure! The consensus API proposal seems to be something like:

* `HashSums` is a filter that takes a `hash.Hasher` and produces hashes of the files named on each line
* `Hash` is a sink that takes a `hash.Hasher` and produces a hash of the pipe's data

**Comment by mahadzaryab1** [comment]
@bitfield Should the `hash.Hasher` input type be a pointer? Or should we take it in as variadic parameter and run all the hashers that are provided?

**Comment by mahadzaryab1** [comment]
@bitfield I've got a PR ready for review at https://github.com/bitfield/script/pull/215.

**Comment by bitfield** [comment]
@terrorbyte what do you think of the changes in #215? Do they solve the problem for you?

**Comment by terrorbyte** [comment]
I think that using the `hash.Hash` interface is much smarter and allows for some definition of parameterized hashing. I'd sign off on this in general, but wonder if we should provide an example of how to define a `hash.Hash` for something like [argon2i](https://pkg.go.dev/golang.org/x/crypto@v0.27.0/argon2) to have an example of how you could use parameterized hashing algorithms. It's also probably better to leave that open ended for specific user use cases.

Good work @mahadzaryab1
