### ISSUE TITLE
I am missing "tee"

### ISSUE THREAD

**Issue by oderwat** [bitfield/script#145]
I know we can write a filter for it, but having `tee` in the set of filter would be nice.

**Comment by bitfield** [comment]
Great idea, @oderwat! How do you envisage this looking from the user's perspective?

```go
script.Echo("hello").Tee(some_io_writer).Stdout()
```

Something like this?

**Comment by bitfield** [comment]
Let's look at this from the point of view of some real-world program that we'd like to write. Can you think of a situation where someone would want output to go to two places in a script? What kind of data would this be, where would it come from, and where would it need to go to?

**Comment by oderwat** [comment]
Well, I need it to see what is getting written to the files after using Exec and replace operations of its output. Basically, to show what the script does. I do the same with `tee` all the time, like:

```
python somescript.py ./some/dir | tee logfile.log
```

So, when using "script" the harder and possibly error causing part is the writing of the file and this is easiest done as:

```
script.Exec("python somescript.py ./some/dir").WriteFile("logfile.log")
```

But that means I can't see the output. I would need to re-open the file or store everything in a string first. Or use a filter that copies it from in to out and prints it to stdout. So from my point of view, the usual thing is probing. You also may want to write out the current data at different places in the chain to debug or log the process in the chain.

I think your initial understanding about what Tee should do is good. One could implement it with variable argument function like `Tee(w ...io.Writer)` and default it to os.Stdout if it gets an empty slice. If there is a slice, it could send it to all writers (which could be io.Stderr too).

**Comment by bitfield** [comment]
Right! For the time being, as you say, you can copy the data to the terminal using:

```go
script.Echo(data).FilterScan(func(line string, w io.Writer) {
	fmt.Println(line)
}).AppendFile("logfile.log")
```

**Comment by rmasci** [comment]
Those filter commands are powerful. I needed something like this but for each line I found in my /etc/hosts that matched an sdn system. What was cool is that in the function run by 'filterline' I could do another script.Exec. This also shows that the function doesn't have to be inline, but could be a separate function, could be in a different file -- may be 100+ lines long. 
```
func main() {
	re := regexp.MustCompile("prod[\t\r\n\f]")
	script.File("/etc/hosts").Match("sdn").MatchRegexp(re).Column(2).FilterLine(isPortOpen).AppendFile("Output.txt")
}
func isPortOpen(s string) string {
	str, _ := script.Exec("tcpscan -O text " + s + " -p 22").String()
	str = strings.TrimSpace(str)
	fmt.Println(str)
	return str
}
```
Output to both screen and Output.txt:
```
sdn-east-host1-prod 22 Open 143.80ms
sdn-west-host1-prod 22 Open 103.58ms
sdn-east-host2-prod 22 Open 143.80ms
sdn-west-host2-prod 22 Open 103.58ms
...and so on...

**Comment by rmasci** [comment]
``` sdn-east-host1-prod 22 Open 143.80ms
sdn-west-host1-prod 22 Open 103.58ms

**Comment by bitfield** [comment]
@Meandi-n, can you show an example of how this would be used in a program?

**Comment by Meandi-n** [comment]
Hi, 
For instance (as the commenter above stated): if you wanted to `WriteFile` a result, while still displaying it to the user terminal...

```
script.Echo("hello world").Tee("output.txt").Stdout()
```

Is this the direction you were thinking of going?

**Comment by rmasci** [comment]
What if I don't want the file truncated? What if I want the results put to my main log file? Or I want one file, for several different script.Exec().Tee()? Passing a writer gives the programmer the flexibility of how the file is open and the ability to error before the pipeline if the file can't be open / written to.

**Comment by Meandi-n** [comment]
> That sounds okay, but maybe it would be more flexible to have `Tee` take any `io.Writer`, instead of being restricted to files?

That's a really good point, I'll try write something to that affect

**Comment by rmasci** [comment]
I forked script into my repsitory, I added a Tee function to it, and added a test for it in script_test.go. 

```
script] $ go test -v | grep -i tee
=== RUN   TestTeeOutput
=== PAUSE TestTeeOutput
=== CONT  TestTeeOutput
--- PASS: TestTeeOutput (0.01s)
```

 If Bitfield could review it I could issue a pull request -- just want to make sure that's ok with him before I do a pull request.
https://github.com/rmasci/script

**Comment by Meandi-n** [comment]
I wrote an implementation exactly the same as rmasci earlier today. 
used as follows:
```
data := "Hello World"
path := "test.txt"
out, err := os.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0666)
if err != nil {
	panic(err)
}
script.Echo(data).Tee(out).Stdout()
```
I like this implementation. its simple and flexible, I think it will make some scripts much cleaner. 
I hope Bitfield feels the same.

**Comment by bitfield** [comment]
Something like `TeeFile` might be a useful shorthand, mightn't it?

**Comment by Meandi-n** [comment]
`Tee(<io.Writer>)` and `TeeFile(<path>)`

Would TeeFile amend the file (useful for updating logs) or write the file? 

The end user could select via passing the mode as an input, or alternatively by calling `TeeFileAmend()` or `TeeFileWrite()`. 

Would this be too complex?

**Comment by bitfield** [comment]
The append behaviour sounds more useful, doesn't it? This sort of design problem is always a case of drawing a fine line between what's useful, and what inflates the API more than it's worth.

**Comment by gedw99** [comment]
> That sounds okay, but maybe it would be more flexible to have `Tee` take any `io.Writer`, instead of being restricted to files?

Agree

**Comment by gedw99** [comment]
I would like to add “patch”. Append is definitely needed too .

Patch would allow any line to be replaced. 

It allows use to build high level system on top where change events can fire and using path we update a file. 

Then you can do the produce consumer pattern and watch a file for modifications and produce an event of what changed ( basic diff ) and a consumer can consume the file change event in whatever way they need. 

Often a file change can mean you want to kick off other execs. 

it’s recursive too because those other execs that are kicked off might also change a few files. So then another series of file change events fire off and consumers react .

the current architecture is like a RPC design . If we have patching we also get a reactive system. 

I already built the bones of this but don’t want to put it into this repo if it’s not wanted and so I am raising this to see if people like this design pattern to make the system more extensible to wider user cases .

> `Tee(<io.Writer>)` and `TeeFile(<path>)`
> 
> Would TeeFile amend the file (useful for updating logs) or write the file?
> 
> The end user could select via passing the mode as an input, or alternatively by calling `TeeFileAmend()` or `TeeFileWrite()`.
> 
> Would this be too complex?

This is awesome

**Comment by gedw99** [comment]
> `Tee(<io.Writer>)` and `TeeFile(<path>)`
> 
> Would TeeFile amend the file (useful for updating logs) or write the file?
> 
> The end user could select via passing the mode as an input, or alternatively by calling `TeeFileAmend()` or `TeeFileWrite()`.
> 
> Would this be too complex?

Quite like this . Can be extended further by other too I think . Good pattern

**Comment by gedw99** [comment]
I could add patching on top of this pattern

**Comment by gedw99** [comment]
ah i see your point.

Maybe we can provide both options ??  Or is that making the APi too confusing... Not sure...

**Comment by gedw99** [comment]
I was also thinking of the debugging aspects too when i saw this :)

I have a few ideas around this too, and will prob make a repo showing doing patching, appending, etc. I want to put a produced / consumer model around this. So like your the consumer can be for scp, or it could be some other protocol.
