### ISSUE TITLE
Script：No method to judge file or dir

### ISSUE THREAD

**Issue by zjzjzjzj1874** [bitfield/script#147]
When I use the testdata which `script` provided,`pipe` just show theirs name or path,is there any methods can I judge file or folder them are? Please show me how can I solve with `script`,tks!
![Uploading image.png…]()

**Comment by zjzjzjzj1874** [comment]
![31669885804_ pic](https://user-images.githubusercontent.com/47138343/205012677-8d8a23f2-4365-4839-ad9e-912155e5fc74.jpg)
Here is this pic.

**Comment by bitfield** [comment]
Sorry, I'm not quite following what you're asking for. Could you show the code you're using and say what you'd like it to do?

**Comment by zjzjzjzj1874** [comment]
<img width="573" alt="WechatIMG86" src="https://user-images.githubusercontent.com/47138343/205564773-9a045934-bb45-4dbd-bbb5-d9ca37676a67.png">
In this pic above I used,`script.ListFiles(path)`just list all objects.If I want to differentiate between files and folders,is there another friendly ways,if exist pls show me,tks very much!

**Comment by bitfield** [comment]
Ah, I see. At the moment there's no `script`-specific way to do that; you can use the standard library `os.Stat` on each path instead.

**Comment by zjzjzjzj1874** [comment]
got it,tks very much.    ^_^
