### ISSUE TITLE
MustString, MustStdout, etc

### ISSUE THREAD

**Issue by oderwat** [bitfield/script#156]
While using `script`, I think that it would make stuff easier if we get `MustString()` `MustStdout()` and similar constructs. In prototyping, my team and I are using a simple `must.OK()`, `must.OKOne()` package to keep the code terse. Currently, we end up writing a lot of:

```go
goVersion := must.OkOne(script.Get("https://go.dev/VERSION?m=text").String())
```

Which would be much more elegant as:

```go
goVersion := script.Get("https://go.dev/VERSION?m=text").MustString()
```

The same applies to the other sinks.

**Comment by oderwat** [comment]
I mostly also just use the second way!

> Because of this, it usually doesn't make sense to recover such panics, because they signal that the program is in some unexpected, unexplained, and unknown state

Not necessarily the program, just a part of your program. That is quite a difference.

Your example with `log.Fatal()` is just terrible, and this is not about the verbosity.

It does not let you recover, test your code or see where it happens. So, you need to use a panic there or add more to the output to make this an useable sub routine.

So in that example, you may need to `panic(err)` anyway. We do, and in many places :). What really would make a difference is when you use panic and wrapping the error code in that case.

I sometime use fatal in programs that are being used by other people. But I wrap it in a function that uses the runtime to tell the file and line, where they `log.Fatal()` was being called. This way you can actually see where that happened and don't dump a stack trace to the poor user in that case. Lately, I just ditched that, though because `os.Exit()` just does not cut it most of the time.

Going back to `script`. This module is called "script" and when you write scripts and need stuff getting done, you just do `set -e` and if something goes bad, it stops there. `cd somedir || exit 1` is another example of what "scripting" is like in numerous instances.

As said: I agree 100% with your point. Added that when writing code that needs clean-up (like any kind of servers or applications) you need a recover system at some point. We all hate "crash to desktop".

But, for code that is "write / use / delete", there are better things to do, that to test for errors everywhere. So, I think that adding it to your package does not mean that you tell people to use it. But this is the "one change" people can't make themselves as `*Pipe` is not extensible from outside your package.

Still, if that is not what you want to add to your code, I am fine with it. I already forged it for our usage. I just wanted to contribute, because of us using your work. Thank you for that.

BTW: While adding my MustXXX code. I saw places where you do not check errors and was tempting to add them in. But

**Comment by bitfield** [comment]
I appreciate you taking the time to critique my "just terrible" code. Not everyone would be so generous.

Let's leave this open for now to gather a few more views and see how people feel about having this facility.

**Comment by oderwat** [comment]
You lecture me about panics and give an example with log. Fatal ... Come on!

**Comment by bitfield** [comment]
I understand it's upsetting when your suggestion isn't accepted—believe me, I know what that's like! However, it _is_ welcome and it _is_ valued, so, as I say, I'm leaving the issue open to gather feedback from other users.

All the same, your recent interactions haven't lived up to the spirit of our [Code of Conduct](https://github.com/bitfield/script/blob/d5e838dc75d00c4b6f835ff0c138d5fbf06a8086/CODE_OF_CONDUCT.md), so I've put a temporary block on you, just to give a pause for reflection and let emotions cool a little. I want to emphasise that this _is_ temporary, and if and when you decide you're willing to abide by the CoC, you'll be most welcome to return to the project and continue making good contributions.

**Comment by oderwat** [comment]
You are welcome to create this issue by yourself. I do not have an issue with it anymore.
