### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by gedw99** [bitfield/script#164]
https://github.com/bitfield/script#quick-start-unix-equivalents

When you click the links on a mobile it’s not going to the right place 

maybe use GitHub pages and gen the go doc into the GitHub pages.

I suspect the cause is versioning but not sure

**Comment by bitfield** [comment]
When you say "not going to the right place", can you point to an example?

**Comment by gedw99** [comment]
seems to be working now.

did not before... cloning :)
