### ISSUE TITLE
Replace lines in plain-text file by line number

### ISSUE THREAD

**Issue by Meandi-n** [bitfield/script#165]
Hi everyone, 

I'm attempting to use script to automatically edit some configuration files on my system. 
I don't see a method in the documentation to easily rewrite lines of a plain-text file.

An operation equivalent to the following command in bash:
```
replace="replacement_string"
line="4"
#replacement command
sed -i "${line}s/.*/${replace}/" config.txt
```

Is this a feasible command to implement?

**Comment by Meandi-n** [comment]
Don't Replace or ReplaceRegexp operate by searching for matching strings and replacing?
I'm searching for a method to replace lines of plain-text by specifying line number.

**Comment by bitfield** [comment]
Sorry, I misunderstood what you were asking for. How about something like this:

```go
	lineNo := 0
	script.Echo("line 1\nline 2\nline 3").
		FilterLine(func(s string) string {
			lineNo++
			if lineNo == 2 {
				return "updated line 2"
			}
			return s
		}).Stdout()
```

https://go.dev/play/p/dWMcTPESzxU
