### ISSUE TITLE
script.Exec - no colours on stdout

### ISSUE THREAD

**Issue by indaco** [bitfield/script#168]
Executing system commands printing colourful messages on stdout, the output does not preserve the colours.

```go
_, err:= script.Exec("npm install").Stdout()
```
How to do that?

Thanks

**Comment by bitfield** [comment]
Hi, @indaco, thanks for the report!

Most programs that produce coloured output can also detect whether or not they're talking to an interactive terminal (for example, [`gotestdox`](https://github.com/bitfield/gotestdox). If not, they reason, there is no point producing colour codes, since it only makes sense to set colours when the output goes to a terminal.

In this case, the output of `npm install` is _not_ going to a terminal, so it has presumably decided not to use colour mode. There may be ways to change its mind. Have you tried setting the `FORCE_COLOR` variable as described here? https://github.com/nodejs/node/issues/37404

**Comment by indaco** [comment]
Hi @bitfield thanks for the proper response.

For sure, I'm in wrong but...the reason why I am asking how to achieve it with _script_ is simply because, using something like

```golang
package main

func ExecCmd(cmdName string, cmdOptions string, silentMode bool) error {
	var cmd *exec.Cmd

	args := strings.Split(cmdOptions, " ")
	cmd = exec.Command(cmdName, args[0:]...)
	cmd.Stderr = os.Stderr

	if !silentMode {
		cmd.Stdout = os.Stdout
	}

	err := cmd.Start()
	if err != nil {
		return err
	}

	return cmd.Wait()
}
``` 

I got the output with colours preserved.

What am I missing?

**Comment by bitfield** [comment]
Your code sets the command's `Stdout` stream to `os.Stdout`... which _is_ a terminal! (At least, it will be when you run this program from the command line.) So when the program asks "Is my standard output an interactive terminal?", the answer is yes.

By contrast, in a `script` pipeline, the command's `Stdout` stream is always the pipe—which is the point of `script`, of course. 

`script` is not doing anything special here; it just reads bytes and passes them on. If the originating command decides to send bytes corresponding to ANSI terminal control codes, `script` will faithfully reproduce them. If not, not. Does that help explain what's going on?

**Comment by indaco** [comment]
Got the point, I guess, thanks.

One more...

My initial thought was

```golang
pipe := script.NewPipe().WithStdout(os.Stdout)
pipe.exec("...").Stdout()
```

would get the same result of my code, then going thought the documentation

`func (p *Pipe) WithStdout(w io.Writer) *Pipe` 

_sets the pipe's standard output to the writer w, instead of the default `os.Stdout`_

Does it mean the default `Stdout` stream is set to `os.Stdout`, right? Is this not the same as set the command's `Stdout` stream to `os.Stdout`?

I am missing something, no doubts...buggy brain

**Comment by bitfield** [comment]
`WithStdout` sets the _pipe's_ standard output (that is, where things will go when you call `Stdout`). That already defaults to `os.Stdout`, which makes sense.

This has no effect on the standard output of _commands_ run by `Exec`.

If setting `FORCE_COLOR` solves your problem, I'll be happy to hear about it.

**Comment by indaco** [comment]
yes, setting `FORCE_COLOR` solves the problem, I was sure about that! 

I was trying to understand...anyhow, thanks for your time and for the _script_ package. I'm going to replace my custom code with it.
