### ISSUE TITLE
[Feature Request] stderr

### ISSUE THREAD

**Issue by Xaelias** [bitfield/script#17]
Yo!
I'm gonna start with an easy one because my golang was never great to begin with, and now I'm rusty :-D

I think you really need an stderr.
There are a lot of use cases. Differentiate between regular output and error output. Output logs to stderr vs data output on stdout, etc. etc.
It's also a very easy addition (again, rusty go).

Unless you have a strong opposition to this, I'll start working on a PR (still reading through your contributor guidelines).

**Comment by bitfield** [comment]
Thanks for the suggestion! To help us flesh out exactly how the API should look, can you give a small sample program where this is used?

**Comment by Xaelias** [comment]
Yeah I'm trying to think of an example that's not just "cat something to stderr".
One of the reason is to keep some compatibility with regular command line tools. And I was actually a bit surprised you decided to have `exec` merge stdout and stderr for that reason.
I'll try to come up with something useful before I put up a PR :-)

**Comment by bitfield** [comment]
It's traditional to separate stdout and stderr from commands, but I can't recall a time when I actually used that. And it's hard to design a good way to do it in `script` (see #16 for discussion about how to handle two pipes).

**Comment by bitfield** [comment]
Closing this as it suffers from the same two-pipe problem (as Sherlock Holmes might have put it) as #16.
