### ISSUE TITLE
gitignore entry for Intellij IDEA 

### ISSUE THREAD

**Issue by vahidR** [bitfield/script#173]
Hi all,

I just cloned your fantastic repo, and as IntelliJ is my primary IDE, it created the **.idea/** folder in the root of the repo. 
Would you please add  **.idea** to the list of gitignore entries? Probably it's not worth a pull request :) 

Cheers,
Vahid

**Comment by bitfield** [comment]
Thanks for the suggestion, @vahidR! Was there something specific you planned to work on using your clone of the repo? If you have a PR in mind for something else, perhaps your `.gitignore` update could form part of that.

**Comment by vahidR** [comment]
Hello John, 

I was just browsing this library and it really got my attention. Amazing idea indeed. 
Nothing specific in my mind right now TBH, just lack of **.idea** in the gitignore got my attention...

**Comment by bitfield** [comment]
No problem. I think setting up a [global .gitignore file](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/) is probably the way to go on this one, rather than adding files to every single project you ever open—but that's up to you, of course.

**Comment by vahidR** [comment]
That's right...
