### ISSUE TITLE
Race condition in Pipe.Exec

### ISSUE THREAD

**Issue by nclv** [bitfield/script#193]
```
WARNING: DATA RACE
Read at 0x00c000036110 by goroutine 55:
  go/pkg/mod/github.com/bitfield/script@v0.22.0/script.go:388 +0x1e9
  github.com/bitfield/script.(*Pipe).Filter.func1()
      go/pkg/mod/github.com/bitfield/script@v0.22.0/script.go:484 +0xc7

Previous write at 0x00c000036110 by goroutine 49:
  github.com/bitfield/script.(*Pipe).WithStderr()
      go/pkg/mod/github.com/bitfield/script@v0.22.0/script.go:887 +0x798
```

There seems to be a data race with stdErr when executing the following piece of code in parallel (test with errgroup).
```go
stdOut := new(bytes.Buffer)
stdErr := new(bytes.Buffer)

if _, err := script.Exec(cmdLine).WithStdout(stdOut).WithStderr(stdErr).Stdout(); err != nil {
	return nil, err
}
```

**Comment by bitfield** [comment]
Good spotting, @nclv! 

It doesn't really make a lot of sense to set the pipe's stdout or stderr _after_ you've already started some command—you may or may not lose some of the output, depending on timing. The more reliable way to do this would be to set the preferred outputs first:

```go
script.NewPipe().WithStdout(stdOut).WithStderr(stdErr).Exec(cmdLine).Stdout()
```

A data race still exists, of course: this merely adjusts the odds in your favour. The pipe already has a mutex, so we could use this to protect these fields. I'll have a look.

**Comment by mahadzaryab1** [comment]
@bitfield does this still need to be worked on! i'd like to contribute if its up for grabs

**Comment by bitfield** [comment]
Yes, you could start by writing a test that proves the data race, if you like.

**Comment by mahadzaryab1** [comment]
@bitfield opened a PR for the fix at https://github.com/bitfield/script/pull/209

**Comment by mahadzaryab1** [comment]
@bitfield the PR is ready for another review whenever you get a chance to have a look!
