### ISSUE TITLE
Conditinally execute statements.

### ISSUE THREAD

**Issue by HARDY8118** [bitfield/script#195]
An `if`...`fi` block to execute statements conditionally can be added. For example:
```go
script
    .If(script.File("key.txt")=="")
    .Then()
        .Echo(token)
        .WriteFile("key.txt")
    .Fi()
```

Please let me know if this can be useful.

**Comment by HARDY8118** [comment]
I can give a try implementing it

**Comment by mahadzaryab1** [comment]
@bitfield What's the status of this? Is it still something we want to add to the package?

**Comment by bitfield** [comment]
I haven't yet seen any evidence that the lack of this feature is a significant problem for a large group of users. I think until we have that, there are probably higher priority things to work on.
