### ISSUE TITLE
"If X exists"

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#20]
Like shell `[ -f X ]`.

**Comment by bitfield** [comment]
I'd love some suggestions for what this might look like!

**Comment by frioux** [comment]
Wouldn't it be something like:

```golang
func IsFile(path string) (bool, error) {
   s, err := os.Stat(path)
   if err != nil {
       if os.IsNotExist(err) {
          return false, nil
       }
       return false, err
   }

   return !s.IsDir(), nil
}
```

**Comment by bitfield** [comment]
Sorry—my fault for not being clear. Yes, the implementation would probably look something like what you quoted, though we need to think about whether we should consider both files and directories to 'exist'.

The more difficult question is about how it would work within `script` pipelines. For example, would it be something like:

```go
script.IfExists("/srv/foo/config.txt").Exec("/usr/bin/configure-service")
```

What do you think? A use case would be helpful here. Have you ever written a script which has logic based on whether or not a file exists?

**Comment by frioux** [comment]
Here are some examples I have on hand (in shell:)

```bash
if [ -f $x ]; then
     cat $x
else
     ls $x --color
fi

if [ -f "$HOME/.goobook_auth.json" ]; then
   goobook query '' >> "$TMP"
   < $TMP grep -v '^ ' | sponge $TMP
fi

if [ -f "$HOME/.dbic.json" ]; then
   export DBIC_TRACE_PROFILE="$HOME/.dbic.json"
fi

if [[ ! -f ~/.dotfilecheck ]]; then
   echo $(($EPOCHSECONDS+60*60*24*7)) > ~/.dotfilecheck
fi
```

**Comment by bitfield** [comment]
Great! Would you mind writing out one of these examples using `script`, as you would like to see it?

**Comment by bitfield** [comment]
@frioux (or anyone else) do you have any comments on the proposed design?

**Comment by frioux** [comment]
I don't use script, this just seemed easy enough to implement that I didn't
understand the outstanding issue.

-- 
Sent from a rotary phone rented from Ma Bell

**Comment by bitfield** [comment]
Well, then it's even more helpful of you to pop in and make suggestions! I appreciate it.

Here's the [final result](https://github.com/bitfield/script/blob/master/sources.go#L32):

```go
// IfExists tests whether the specified file exists, and returns a pipe whose
// error status reflects the result. If the file doesn't exist, the pipe's error
// status will be set, and if the file does exist, the pipe will have no error
// status.
func IfExists(filename string) *Pipe {
	_, err := os.Stat(filename)
	if err != nil {
		return NewPipe().WithError(err)
	}
	return NewPipe()
}
```
