### ISSUE TITLE
ForEach accepting Go function vs. string

### ISSUE THREAD

**Issue by refaktor** [bitfield/script#213]
Hi, great library and tool ... I'm integrating it into my workflow (and scripting language).

Maybe I don't see a whole picture, but wouldn't it make sense to have something like ExecForEach where I can stay in Go in script library for each linek and not be moved down or back to strings for regular shell commands?

**Comment by bitfield** [comment]
@refaktor thanks! I'm not sure if I understand exactly what you're asking for. Could you provide a sample of the kind of thing you'd like to write with `script`?

**Comment by refaktor** [comment]
Maybe I don't understand what Pipe in this case really is, I haven't delved deeper yet. If that is the case, I'm sorry. 

I meant something more like this: 
```
script.FindFiles("messages").NewForEach(function(p *script.Pipe) { script.File(p.String()).Match("Hello:").Stdout() })
```
or maybe
```
script.FindFiles("messages").NewForEach(function(line string) { script.File(line).Match("Hello:").Stdout() })
```

**Comment by bitfield** [comment]
This might do what you want:

```go
script.FindFiles("messages").Match("Hello:").Stdout()
```

And in general, to filter a pipe through any Go function, line by line:

```go
script.FindFiles("messages").Concat().FilterScan(func(line string, w io.Writer) {
	fmt.Fprintf(w, "scanned line: %q\n", line)
}).Stdout()
```

Does this help?
