### ISSUE TITLE
`ExecForEach`

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#22]
Equivalent to shell `xargs`. For example, this use case: https://gist.github.com/Skraelingjar/9aabc58aa26f5b814411e69d67b342fe

**Comment by gagneet** [comment]
Would like to help out on this.

**Comment by bitfield** [comment]
Great! Thanks @gagneet. One thing you could do to get the ball rolling is to write a short `script` program, which assumes the existence of `ExecForEach`, or whatever we decide to name it, along the lines of the linked use case. Once we're happy with the design, we can then write a test for it.

**Comment by mainawycliffe** [comment]
I am thinking the `func` would look roughly something like this:

```go
func (p *Pipe) Xargs(cmd ...string) *Pipe {
	// do something with the output of the previous command
}
```

or 

```go
func (p *Pipe) Xargs(cmd string) *Pipe {
	// do something with the output of the previous command
}
```

This would take a Pipe and use its output to perform more commands. I am still thinking through, as I look to find more scenarios that the `Xargs` commands can be used in.

**Comment by mainawycliffe** [comment]
@bitfield what do you think?

**Comment by bitfield** [comment]
I think using `ExecForEach` should be more or less exactly like using `Exec()`, but with the addition of a placeholder value in the supplied command. In fact, why don't we use Go template syntax, which is even more powerful?

```go
script.ListFiles("*.php").ExecForEach("php {{ . }}").Stdout()
```
