### ISSUE TITLE
Implement 'find TODOs' example

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#23]
https://spin.atomicobject.com/2019/07/17/script-find-todos-code/#.XS8eSdFwrY0.hackernews

**Comment by mainawycliffe** [comment]
This is interesting to me, I can take it up and attempt to find a solution.

**Comment by bitfield** [comment]
I'm looking forward to seeing what you come up with @mainawycliffe! If you're not sure how to get started, here's what I do: I write the program that I'd like to write with `script` first, and then worry about how to implement it! That means by the time I come to implement a method, I already know what arguments it takes, what it does, and what it returns.

**Comment by bitfield** [comment]
@mainawycliffe any news on this? Let me know if you'd like some help.

**Comment by mainawycliffe** [comment]
@bitfield not yet, been working on it mainly weekends. I have a working script and I just need to expand it a little bit so it can work with more comments type and able to get complete todo messages when they span across multiple lines. I hope to have a working prototype over the next weekend and then we can see where we can make improvements.

**Comment by bitfield** [comment]
Sounds great @mainawycliffe! Feel free to share your work in progress with me via john@bitfieldconsulting.com, I may be able to make some suggestions.

**Comment by mainawycliffe** [comment]
I will, Thanks.

Regards
Maina Wycliffe

________________________________

**Comment by bitfield** [comment]
I think this is effectively solved in #36, isn't it?
