### ISSUE TITLE
Prevent Concat from stopping at first error?

### ISSUE THREAD

**Issue by udhos** [bitfield/script#26]
I am trying to use script.Concat() to implement 'cat':

```
        if _, err := script.Slice(flagSet.Args()).Concat().Stdout(); err != nil {
                fmt.Printf("cat: %v\n", err)
                status = 5
        }
```

Full code: https://github.com/udhos/conbox/blob/master/applets/cat/run.go

However I would like to tell Concat() to keep trying other files in case of failure. 

Can we make the behavior configurable?

**Comment by bitfield** [comment]
What do you mean by 'failure'? Concat ignores any files which can't be opened, but will continue to try to open all the files listed. The result will be an [io.MultiReader](https://golang.org/pkg/io/#MultiReader) which reads sequentially from all the files which were successfully opened.

If one of _those_ files throws an error on reading, the MultiReader will return that error. Are you saying that you'd like to be able to skip that error and continue to the next file automatically?

**Comment by udhos** [comment]
I would like to use Concat to mimic the behavior of cat.

cat outputs the contents of file 'hello' even when the first file 'file-does-not-exist' is not present:

```
lab@ubu1-teste-ssm:/tmp/tmp$ echo world > hello
lab@ubu1-teste-ssm:/tmp/tmp$ cat file-does-not-exist hello
cat: file-does-not-exist: No such file or directory
world
lab@ubu1-teste-ssm:/tmp/tmp$
```

But Concat stops after first failure (file does not exist):

```
lab@ubu1-teste-ssm:/tmp/tmp$ more main.go
package main

import (
        "github.com/bitfield/script"
)

func main() {
        script.Args().Concat().Stdout()
}
lab@ubu1-teste-ssm:/tmp/tmp$
lab@ubu1-teste-ssm:/tmp/tmp$ go run main.go hello
world
lab@ubu1-teste-ssm:/tmp/tmp$ go run main.go file-does-not-exist hello
lab@ubu1-teste-ssm:/tmp/tmp$
```

**Comment by bitfield** [comment]
Ah, I get it now. Actually, what I said was wrong:

> Concat ignores any files which can't be opened, but will continue to try to open all the files listed.

That's what it _should_ do (and what you're asking for it to do), but not in fact what it actually does:

```go
	p.EachLine(func(line string, out *strings.Builder) {
		input, err := os.Open(line)
		if err != nil {
			p.SetError(err)
			return
		}
		...
```

I'm not quite sure what we should do here instead. It seems wrong to hide the error completely; maybe we should set the pipe error status, but still continue?

**Comment by bitfield** [comment]
Thanks, @udhos!
