### ISSUE TITLE
calc md5hash of file

### ISSUE THREAD

**Issue by hariboyapally** [bitfield/script#39]
there is always a use case to calculate md5hash of a  file and compare it with others. Having a single liner will definitely help several use cases.

**Comment by bitfield** [comment]
Hey @hredd00, great idea! Thank you!

Since MD5 is not cryptographically secure, maybe we should think about using a newer and more secure hash algorithm, such as SHA-256?

**Comment by hredd00** [comment]
Agreed that we should have a secure hash like SHA-256; however, in one of my use cases I frequently check file integrity with md5 and achieving the same with SHA-256 is more CPU-intensive.
But Yes; another one-liner for SHA256 :)
Thoughts?

**Comment by bitfield** [comment]
Yes, I think that's probably what most people use it for. My concern is, though, that somebody will see this and use it for some security-sensitive application, which it absolutely isn't suitable for. I wonder just how much more expensive (per megabyte) SHA-256 is. Are there any figures on this?

**Comment by bitfield** [comment]
(For example, think about a tool like `tripwire`, which calculates hash sums for installed binaries and uses these to verify that the binary hasn't been modified. MD5/SHA-1 is absolutely unsuitable for this, since you can construct a hacked binary which hashes to the required value.)

**Comment by natea123** [comment]
Hello,

Very much new to open-source contributing but learning Go and would like to take a crack at this. Is the goal to just have a one-liner that returns the sha256 hash of a selected file? I noticed there is a sha256 package [1], would it be viable to use that package for implementation?

[1] https://golang.org/pkg/crypto/sha256/

**Comment by thomaspoignant** [comment]
The `SHA256Sum` is merged, @hredd00 you can use it to calculate files hashes.

**Comment by etimoz** [comment]
Is the md5 hashsum feature still wanted? Would work on it if yes, otherwise I think this issue can be closed.

Correct my if I'm wrong but I think it could still be used to check file integrity see this discussion on [stackoverflow](https://security.stackexchange.com/questions/87375/why-are-md5-and-sha-1-still-used-for-checksums-and-certificates-if-they-are-call).

**Comment by bitfield** [comment]
@etimoz the feature is still wanted by lots of people, I'm sure, but I don't plan to add it to the library. It's pretty easy to write yourself if you want it (following the example of `SHA256Sum`), but if it were in the library I think it would encourage people to use it, which they shouldn't. _We_ know it's relatively safe to use MD5 for checking file integrity, but once you start doing that, someone might see that code and think "That's just what I need to hash my password..." 

So yes, I'll close it. Thanks for the reminder, and happy `script`ing!
