### ISSUE TITLE
Add 'Slice()' sink method to get pipe contents as a slice of string

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#45]

**Comment by thomaspoignant** [comment]
@bitfield I can do it if you want.
Just to be sure, this is just a split on the end of the line like this? https://github.com/bitfield/script/blob/34cdc5b9b45f9810cd0ce9ebf9e2a0f063ec271d/examples/sha256sum/main.go#L19

**Comment by bitfield** [comment]
Something like that should work, yes!

**Comment by thomaspoignant** [comment]
I have open a PR (#47) for that.

**Comment by mrKappen** [comment]
hey @bitfield, I think this issue can be closed as the PR addressing it has already been merged

**Comment by bitfield** [comment]
Thanks @mrKappen! You're quite right. My commit message at 9847d19e69d72d73b191e1f3c65d5dba94605a1c was wrong; it mentioned #47 instead of #45, so this issue wasn't auto-closed.
