### ISSUE TITLE
find difference of two text files

### ISSUE THREAD

**Issue by hariboyapally** [bitfield/script#46]
> What if we want to compare two text files and display the file differences.

**Comment by bitfield** [comment]
That's a great idea, @hredd00! Thanks for the issue.

Would you comment here with a short code example showing how you'd like this to work?

**Comment by hredd00** [comment]
`func diff(soureFolderPath string, destFolderPath string) string {`
` //returns the file differences as below -- `
`}`

> return as below

`++ differences from soureFolderPath`
`--differences from destFolderPath`

**Comment by bitfield** [comment]
Most everything in the `script` library is either a function that creates a pipe, or a method on a pipe. How would you fit `diff` into this framework?

**Comment by fabiodcorreia** [comment]
Maybe something like
``
listOfDiffs, err := script.File("test.txt").Diff("test2.txt").Compare()
``
or 
``
listOfDiffs, err := script.Diff("test.txt", "test2.txt").Compare()
``

**Comment by bitfield** [comment]
It's often helpful to think about what the equivalent shell script would be. Can you think of an example program you'd write as a shell script that uses `diff`, and we'll see how it might translate into `script`.

**Comment by ollien** [comment]
If we're comparing this to the `diff` utility, it might be something like

`script.File("a.txt").Diff(script.File("b.txt"))`

but I think this breaks the paradigm slightly

**Comment by bitfield** [comment]
Yes, I don't really see a good way to incorporate this into `script` at the moment. The `go-cmp` library already provides an excellent `Diff`, for example. I'm open to suggestions, but I think until we have a workable design, this has to remain on hold.
