### ISSUE TITLE
Directory Manipulations

### ISSUE THREAD

**Issue by CSenshi** [bitfield/script#48]
As far as I can see, There is no implementations of directory manipulations. I can see that given API is more about pipelines and one liners, but I can assure that it will be quite handy time to time and can be useful for anyone who will use script.

I would like to suggest PR that will include two new and a must Unix equivalent functions:
1. cd    - change directory
2. pwd - print working directory

**Comment by bitfield** [comment]
Thanks for the issue @CSenshi! A couple of very interesting ideas there.

Could you give a short example program showing you would like to use these functions in `script`, supposing they were provided?

**Comment by CSenshi** [comment]
1. cd:
`script.ChangeDir("/home/guest")` - it would change your working directory to "/home/guest"

2. pwd:
`script.pwd().stdout()` - would print out your current working directory (e.g. after executing above command it would output "/home/guest")

P.S. I haven't yet thought about name of functions, so ChangeDir() and pwd() would do for now

**Comment by bitfield** [comment]
But we already have `os.Chdir()` and `os.Getwd()`, don't we? What value would this add to that?

**Comment by CSenshi** [comment]
My bad, I read README.md file and thought you only had the commands that are written in "Quick start: Unix equivalents" paragraph.

I would like to contribute to this project, It's awesome! Where can I find the whole list of commands and see what's missing?

**Comment by CSenshi** [comment]
oh okay, I know that they are in os library, I thought you might want it in your script library as well. But as for now I Can see there is no real need for chdir, but pwd would be nice in script library because of pipes. There can be case where someone wants to do some operation on pwd-s output afterwards.

P.S. I would love to contribute to this project, because I think it has potential. I would like to hear If you have any other suggestions.

**Comment by bitfield** [comment]
No problem, you're most welcome to contribute, and keep making suggestions! I'll close this for now, but keep the ideas coming.
