### ISSUE TITLE
sinks.SHA256Sum puts the whole file in-memory

### ISSUE THREAD

**Issue by antoin-m** [bitfield/script#49]
Hi :wave:

It seems that `sinks.SHA256Sum()` puts the whole file in-memory which may be an issue for hashing large files.
For example when adding a 1GB file to the test:
```
root@ef78500374de:/workspaces/script# go test
signal: killed
FAIL    github.com/bitfield/script      16.404s
```

**Comment by mrKappen** [comment]
hey @bitfield, this issue seems to be taken care of. Perhaps it should be closed?

**Comment by bitfield** [comment]
Good point! Thanks @mrKappen.
