### ISSUE TITLE
Add SSH example

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#53]
Many sysadmin tasks involve executing commands via SSH. Add an example program that does this, and identify any useful methods that could be added to `script` to make this easier.

**Comment by sukumar1234** [comment]
Hi @bitfield ,

I am new to Go so please correct me if this is already present.

Consider this example
 We have a package built locally, we want to install it remotely and try out its features
Incase of bash, we can do it in two ways

- Write a script which does all this work and execute it remotely
- Write an inline script while doing ssh

Lets consider
## First case(remote script):
 1 on_remote_script.sh contents
```
sudo apt install <pkg>.deb
dpkg -s <pkg>.deb | grep "is Installed" || exit 1
/usr/bin/pkg_exec health_status
```
2 Execute this script remotely
``` 
scp on_remote_script.sh <pkg>.deb username@ipaddr:
ssh username@ipaddr  bash on_remote_script.sh

## Second case(Inline script):
```
scp <pkg>.deb username@ipaddr:
sudo apt install <pkg>.deb
dpkg -s <pkg>.deb | grep "is Installed" || exit 1
/usr/bin/pkg_exec health_status
EOF
```

So incase of script, we can go ahead and add something like,
## For first case
script.Establishsshconnection(username=<user>, ipaddr=<ipaddr>).runScript(<filename>)

## For Second case
script.Establishsshconnection(username=<user>, ipaddr=<ipaddr>).runInline(
sudo apt install <pkg>.deb
dpkg -s <pkg>.deb | grep "is Installed" || exit 1
/usr/bin/pkg_exec health_status)


Note: All these keeping in mind that ssh is based on key authentication(since we wont least interaction)
We can also have password based authentication(I assume once we have user_input field ready, we can leverage that)

Please let me know if we can leverage existing Go features for constructing these

**Comment by bitfield** [comment]
Hey @sukumar1234, thanks for the constructive suggestion!

Since nearly everything in `script` is a pipe, perhaps this is a more intuitive way to write your second example:

```go
installPkg := `sudo apt install .deb
dpkg -s .deb | grep "is Installed" || exit 1
/usr/bin/pkg_exec health_status`
script.Echo(installPkg).SSH('john', 'test.bitfieldconsulting.com').Stdout()
```

What do you think?

**Comment by sukumar1234** [comment]
Hi @bitfield ,

Makes sense. Now the issue we need to tackle with is ssh authentication
- rsa key based
- password based

1. RSA key based
For this we need to either ask the user to provide the path to their public key. If not provided we search the default path(~/.ssh/id_rsa.pub)
2. Password based
For this we can either have a prompt asking for password( as a raw input) or take it as an argument.


My solution:
1. Key based
- Default path
```
script.Echo(installPkg).SSH('john', 'test.bitfieldconsulting.com').Stdout() 
```
- User specified path
```
script.Echo(installPkg).SSH('john', 'test.bitfieldconsulting.com', path='/opt/.ssh/id_rsa.pub').Stdout()
```

2. Password based
- Ask for password
```
script.Echo(installPkg).SSH('john', 'test.bitfieldconsulting.com').Stdout() 
```
If we need password, we prompt user for password and then continue execution of the script on remote
- provide password as argument
```
script.Echo(installPkg).SSH('john', 'test.bitfieldconsulting.com',password='password').Stdout() 
```

And i think the ssh feature is yet to be implemented, if it isn't then i would like to pick it up.

Do let me know your suggestions

**Comment by bitfield** [comment]
> For this we need to either ask the user to provide the path to their public key. If not provided we search the default path(~/.ssh/id_rsa.pub)

I think we should do whatever the SSH command does (including, somehow, being able to specify a key, or the path to a key file).

> Ask for password

Since `script` is designed primarily for building automation, rather than interactive tools, I'm less sure about this. Password-based SSH is much less secure than key-based, so I'm not inclined to support it.

> And i think the ssh feature is yet to be implemented, if it isn't then i would like to pick it up.

Let's rough out the design first, with a few example programs that show how it would work.

**Comment by sukumar1234** [comment]
> > For this we need to either ask the user to provide the path to their public key. If not provided we search the default path(~/.ssh/id_rsa.pub)
> 
> I think we should do whatever the SSH command does (including, somehow, being able to specify a key, or the path to a key file).
> 
> > Ask for password
> 
> Since `script` is designed primarily for building automation, rather than interactive tools, I'm less sure about this. Password-based SSH is much less secure than key-based, so I'm not inclined to support it.
> yes sure. We can exclude that
> > And i think the ssh feature is yet to be implemented, if it isn't then i would like to pick it up.
> 
> Let's rough out the design first, with a few example programs that show how it would work.
Yes makes sense. I'll work on that

**Comment by sukumar1234** [comment]
Hi @bitfield ,

A small bug in the example i mentioned above: 
- inorder to execute a sudo command, you would need to allot a psuedo terminal (in some cases force a sudo terminal), so we need to take care of that.

Another question, i see that we have a package golang.xorg/x/crypto/ssh. Can we leverage that?

**Comment by bitfield** [comment]
It would be ideal if we didn't require an `ssh` binary to be present as an external dependency. But that depends on how easy it is to replicate the behaviour of `ssh` with the `crypto/ssh` library.
