### ISSUE TITLE
Integrate goreadme

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#54]
https://github.com/apps/goreadme

**Comment by bitfield** [comment]
Certainly!

**Comment by mainawycliffe** [comment]
I am just going through this, I can see there is a number of options to implement this like using GitHub Actions and GitHub Apps. I also think it might be possible to hook it up to any other CI. Do you have any particular preference?

**Comment by bitfield** [comment]
Let's try GitHub Actions! I've been using CircleCI up to now, but my sense is that Actions should be able to replace a lot of what CircleCI currently does.

**Comment by mainawycliffe** [comment]
Yeah, GitHub Actions can replace Circle CI Completely.

**Comment by mrKappen** [comment]
I think this issue can be closed @bitfield

**Comment by bitfield** [comment]
Well, we haven't actually done it yet! If you're looking for something interesting to pick up, @mrKappen, feel free to look at this one!

**Comment by mrKappen** [comment]
oh whoops. I would be happy to take a look @bitfield .

**Comment by mainawycliffe** [comment]
@bitfield I have been playing with goreadme and couldn't get it to generate docs for structure methods, just the top level, structure docs. So I decided to do some digging and came across [gomarkdoc](https://github.com/princjef/gomarkdoc) which does generate the docs as expected, [here](https://github.com/mainawycliffe/script/blob/go-doc/doc.md) are the docs I was able to generate.

**Comment by bitfield** [comment]
Looks awesome @mainawycliffe! Nice job!

Could you run up a PR to move the existing text from the README into a `doc.go` file, and add a GitHub Action to autogenerate the README from it?

**Comment by mainawycliffe** [comment]
Yeah, I think so. Let me work on the GitHub Action workflow and create a PR.

**Comment by mainawycliffe** [comment]
after further play with the gomarkdoc tool, it's possible to generate the complete read me, but it will require moving the package intro section of the read me as a package comment, it works for the most part, but it's not compatible with markdown, but can be adopted to be somewhat decent.

**Comment by bitfield** [comment]
Great! Would you like to try this, and see how far you can get?

**Comment by mainawycliffe** [comment]
Yeah, I would like to do that.
