### ISSUE TITLE
Have FindFiles() take a glob

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#55]
For symmetry with ListFiles().

**Comment by vigneshashokan** [comment]
Hey @bitfield ! Sorry for the delayed response. Before I start work on this, I wanted to clarify a thing.

Directory structure
```
root
├─── root_folder1
│    ├─── root_folder1_file1.txt
│    ├─── root_folder1_file2.txt
│    ├─── root_folder1_sub_folder1
│    │    ├── root_folder1_sub_folder1_file1.txt
│    │    └── root_folder1_sub_folder1_file2.txt
│    └─── root_folder1_sub_folder2
│         ├── root_folder1_sub_folder2_file1.txt
│         └── root_folder1_sub_folder2_file2.txt
└─── root_folder2
```

What is the expected output when I do a FindFiles("/root/*/root_folder1_sub*")?
My understanding is that the glob should be resolved to the actual folder paths, in this case [/root/root_folder1/root_folder1_sub_folder1, /root/root_folder1/root_folder1_sub_folder2] and list all the files under these folders
```
Output:
/root/root_folder1/root_folder1_sub_folder1/root_folder1_sub_folder1_file1.txt
/root/root_folder1/root_folder1_sub_folder1/root_folder1_sub_folder1_file2.txt
/root/root_folder1/root_folder1_sub_folder2/root_folder1_sub_folder2_file1.txt
/root/root_folder1/root_folder1_sub_folder2/root_folder1_sub_folder2_file2.txt
```
so the files /root/root_folder1/root_folder1_file1.txt and /root/root_folder1/root_folder1_file2.txt are not printed.

Is my understanding correct?

(sorry for the long file names)

**Comment by bitfield** [comment]
I'm not quite sure what you're asking.

**Comment by vigneshashokan** [comment]
@bitfield I wanted to understand the issue better. When you say that `FindFiles()` should be able to take a glob, that means,
1. It needs to take an input with wildcard chars like filepath = `/folder1/folder*`, and should list all the files recursively in this path.
2. It needs to take an input without wildcard chars as well like filepath = `/folder1/folder2`, and should list all the files recursively in this path.
Is this correct?

**Comment by bitfield** [comment]
Correct! Basically, it should be the equivalent of ListFiles with a glob, followed by a FindFiles on all its results! (Maybe we could use this as a test.)

**Comment by vigneshashokan** [comment]
Sweet that clears things up, Thanks!

**Comment by vigneshashokan** [comment]
Hi @bitfield, sorry for the delay. I created a PR to fix this https://github.com/bitfield/script/pull/65. Let me know what you think.

**Comment by bitfield** [comment]
Closed because we don't have a use case for this.

**Comment by Robert-M-Muench** [comment]
Why don't we have a use case for this? IMO, the most common use case at all is: *Execute script on all files found with this filename pattern*, and I was recently fighting my way through `script` to get this somehow worked around.

`script.ForAllFiles("**/*.pdf").Exec(...).WriteToFile(<here-I-would-like-to-get-the-filename-of-the-PDF-feed-in)`

**Comment by bitfield** [comment]
What about filtering the files with `MatchRegex`?

**Comment by Robert-M-Muench** [comment]
A package like this makes sense if it saves my considerable time and brain capacity. Most likely, I could use `MatchRegex`. However, the use case I stated is so typical that I want to avoid thinking about how to twist it to make it work.

If the package shifts my brain time from thinking about *how I would do it in Go* to *how I would do it using X* there is not much gained. And I might be quicker, have fewer dependencies, etc., with plain Go.

Don't get me wrong, I like the approach, but it feels too similar to plain Go. Another example is the `stderr` issue. That's mostly a showstopper.

When chaining several commands, another omnipresent question is *how can I get the output of A as input to B?* Like a filename down to the `WriteFile(string) call`?
