### ISSUE TITLE
ListFiles() does not detect file?

### ISSUE THREAD

**Issue by Prepodavan** [bitfield/script#57]
### Case
I have two files in separate folders and one empty folder. Here's output of `tree`
```bash
.
├── a1
│   └── 2.txt
├── a\1
│   └── 1.txt
└── empty

3 directories, 2 files
```
### Code
```golang
package main

import (
	"fmt"
	"github.com/bitfield/script"
	"os"
)

func main() {
	s, _ := script.ListFiles(os.Args[len(os.Args) - 1]).String()
	fmt.Print(s)
}
```
Compiled binary `list_files_test` stored in `$PATH`
### Test
1. `$ list_files_test a1`
**Output**: `a1/2.txt`
**Expected**: `a1/2.txt`
2. `$ list_files_test a\\1`
**Output**: `a1`
**Expected**: `a\1/1.txt` (or `a\\1/1.txt`)
Maybe i misunderstood expected behavior?
### Source of the problem
`ListFiles()` detect this input as glob by  `strings.ContainsAny(path, "[]^*?\\{}!")`. However that is not glob for sure.
And i don't know is that expected or not.

### Additional
This issue related and important to #55.
Let's assume i have input for `FindFiles` such as `/some/abs/path/a\\1/*.txt` (assuming we have same case as i provided at the beginning). By this input i would expect library will interpret folder `a\\1` as root for `filepath.Walk`. Then this walking should find all txt files under folder `a\\1`. But with same way of detecting glob as in `ListFiles` function will take folder `path` as root and then will also find all txt files under folder like `a1` from provided test case. However these files are not in our interests. (Of course assuming we want to check all directories match glob as well, not just file).
Yes, programm could produce expected output if i would check input string in `main` but this input is for just illustrating problem related to #55.
### Workaround
Change way of glob detecting.

**Comment by bitfield** [comment]
Hey @Prepodavan, thanks for the report! If I'm understanding you correctly, you're saying that a path such as `a\\1` is incorrectly detected as a glob, and therefore ListFiles() simply reports the directory as the only match for the glob, rather than listing the files in the directory. Is that right?

So possibly we could fix this by changing the regex which is used to recognise globs?

**Comment by Prepodavan** [comment]
Yes. But user of `ListFiles()` could simply avoid problem this by changing input string on his own (if he knows about this case). And I also tried to say same problem in `FindFiles()` would produce wrong and wouldn't be as easily avoided as in `ListFiles()` if it will use same way of glob recognising as `ListFiles()` use now. So changing the regex which is used to recognise globs is necessary for implementing #55

**Comment by Prepodavan** [comment]
I could fix this issue and implement #55 if u agree with my arguments

**Comment by bitfield** [comment]
Yes, you're most welcome! I suggest you put in a PR which includes a test case for ListFiles which _fails_, demonstrating the problem, and thus also confirming for us when we've successfully fixed it. Once we're happy with the failing test, you can go ahead and make it pass 😄

**Comment by Prepodavan** [comment]
I misinterpreted task. So this issue is not relevant anymore. I guess should be closed

**Comment by bitfield** [comment]
I'm not sure what you mean. I agree with you that a filename containing a backslash should not be interpreted as a glob, and as far as I know that issue still exists. Shouldn't we keep this open, then?

**Comment by Prepodavan** [comment]
Validation of case with input string containing characters of glob is not responsibility of function `script.ListFiles` as same as `filepath.Match` (and `Glob`). That's responsibility of user of this functions. He should escape with `\` these characters if they shouldn't be interpreted as glob. 
This issue was inspired not by `ListFiles` but by #55. I thought impossible to implement #55 without taking responsibility for case with input string with glob characters. Then function `FindFiles` should know where's real glob or just string with characters of glob. Otherwise it would produce wrong output. And i tried to illustrate this problem on existing code (`ListFiles`) even knowing this code is not a source of problem. 
But I finally figured out where I was wrong and how to implement #55 leaving responsibility for this case to the user. 
If I finally understand everything correctly in current implementation of `ListFiles` and in my implementation of `FindFiles` everything will work fine if user will do escaping for chars he dont consider as glob. So I don't think this issue is relevant. 
You still could reopen this if you have some arguments for this. But I haven't
