### ISSUE TITLE
awk filter ( split with columns outputs ), maybe later outputs to charts library

### ISSUE THREAD

**Issue by chinglinwen** [bitfield/script#6]
Hi, This project is great, I've got some idea

Split with columns outputs, with awk mechanism and regexp ? 

Which it can set FS input delimiter and OFS output delimiter, specify which columns to output

This may later working directly send output to charts library? (generrate a graph maybe ) or csv

Here are some chart libraries:

1. https://github.com/vdobler/chart
2. https://github.com/chenjiandongx/go-echarts
3. https://github.com/gizak/termui

I used to write this https://github.com/chinglinwen/k8s/blob/master/testing/httpload/funcs, which I think represent some usecases.

**Comment by bitfield** [comment]
Thanks for the issue! It sounds like you're talking about something like the Unix `cut` tool, is that right? For example, given tabular information like this:

```
PID	User	Command
1	root	init
```

you could use a filter like `Cut(3)` and get:

```go
Command
init
```

**Comment by chinglinwen** [comment]
cut and awk almost do the exactly same things ( for most cases ), though I found cut is hard to use, especially for cut to handle white space and table character.

**Comment by chinglinwen** [comment]
Cut may default to use space and table as separator, it may need others as separator.

**Comment by bitfield** [comment]
@chinglinwen there are some design discussions ongoing about this in #7.

**Comment by bitfield** [comment]
@chinglinwen apart from the newly-added `Column()` support, would `Replace()` and `ReplaceRegexp()` help with your use case? I think actually generating charts is out of scope for the moment, but a program that uses `script` to process the raw data for charts might be a nice example.

**Comment by chinglinwen** [comment]
I guess newly added `Column()` solved part of the issues.  you may label this issue is as a low priority for charts  related works.

**Comment by bitfield** [comment]
OK, great! I'll close this if you don't mind, and you can open a new issue to add the chart-generating example at some point if you like.
