### ISSUE TITLE
Run 3 bat with error

### ISSUE THREAD

**Issue by hziyani84** [bitfield/script#60]
I have batch file call runall.bat  this file will call 3 batches 

Call 1.bat this bat file will download ftp files
Call 2.bat
Call 3.bat

I need to know how to prevent calling 2.bat if 1.bat get error.

And stop call 3.bat if 2.bat ger error
Finaly generate a log file shows process made .

**Comment by bitfield** [comment]
Hi @hziyani84! This sounds more like a question about how to use the `script` library than a problem report with the library itself, is that right?
