### ISSUE TITLE
FindFiles and ListFiles might want to trim newlines from the path

### ISSUE THREAD

**Issue by christophberger** [bitfield/script#62]
Hi @bitfield , thanks for this awesome package. I just ran into an issue that is surely an easy thing to improve.

Issue: the output of Pipe.String() may include a newline. FindFiles and ListFiles cannot find a path that ends in a newline. Hence these two methods cannot consume the output of Pipe.String() without prior removal of newlines.

Suggestion: Have FindFiles and ListFiles trim trailing newlines from the input path.

Example:
```go 
package main

import (
	"log"
	"github.com/bitfield/script"
)

func main() {
	r, _ := script.Args().String()
	log.Printf("args: [%s]\n", r)
	p := script.ListFiles(r)
	_, err := p.Stdout()
	log.Println(err)
}
```
Call:
```
go run main.go .
```
Output: 
```
2020/09/08 13:57:58 args: [.
]
2020/09/08 13:57:58 stat .
: no such file or directory
```
Severity: minor annoyance but can cost time to track down.

**Comment by bitfield** [comment]
Hi @christophberger, nice suggestion, thank you! It seems like there are actually a bunch of pipe sources which could struggle with a newline-terminated string. Maybe another solution is to provide a way to trim the trailing newline from the pipe's output? Ruby and Perl call this `chomp()`, I think. We could do the same. Ideas welcome!

**Comment by christophberger** [comment]
I think you can best decide which approach fits best into the pipe design. My own bias would be towards automatic stripping of newlines from path strings. After all, a file path never contains newlines.

The reason for this bias is that I needed a while to figure out why FindFiles or ListFiles did not seem to work the way they should. Only after adding all the missing error handling and logging, I discovered the trailing newline as the reason for the malfunction. (Yeah, PEBCAK definitely. Lesson learned: Never neglect proper error handling, even for simple throw-away scripts.) If the newlines are stripped automatically, user errors like this one cannot happen anymore.

**Comment by bitfield** [comment]
> Lesson learned: Never neglect proper error handling, even for simple throw-away scripts

As a Go teacher, I naturally agree with this 😁 	

> My own bias would be towards automatic stripping of newlines from path strings. After all, a file path never contains newlines.

That is a very good point, so any method which accepts file paths could trim them automatically.

Are you interested in working on this? If not, no problem, but if you are, we could work together on a PR for the fix.

**Comment by christophberger** [comment]
Hi John,

No problem, I have created a PR <https://github.com/bitfield/script/pull/63> just now. Let me know what you think.

Best,
Christoph
