### ISSUE TITLE
How to use the Pipes for a cli cmd confirmation

### ISSUE THREAD

**Issue by utx0** [bitfield/script#66]
Am new to this package, and am trying to use this for the underlying mechanics of a testing framework for a cli I am building. 

Currently I have this function. 
```
func CreatePool(fromUser,sourceChain,symbol,ticker, nativeAmount,externalAmount string) {
	cmd := fmt.Sprintf("sifnodecli tx clp create-pool --from %v --sourceChain %v --symbol %v --ticker %v --nativeAmount %v --externalAmount %v", fromUser,sourceChain,symbol,ticker, nativeAmount,externalAmount )
	p := script.Exec(cmd)
	p.SetError(nil)
	output, err := p.String()
	if err != nil {
		Fail(err.Error())
	}
	fmt.Println(output)
}
```

However the issue I am having with this cmd is it then requires an input confirmation before executing and the above cancels the cmd. ie

```
confirm transaction before signing and broadcasting [y/N]: 
``` 

Are you able to tell me how I would also automatically pass a `Y` to said cmd? 

Thanks

**Comment by bitfield** [comment]
Yes, that's a tricky one! Perhaps we need something like `ExecWithInput()` that takes a command and a string to feed to its standard input?

**Comment by bitfield** [comment]
(On Linux or Mac, you can trivially pipe the command `yes` to programs like this to give them an affirmative response.)

**Comment by utx0** [comment]
yeah in bash land I would just do 

`yes Y | sifnodecli tx clp create-pool  ...`
