### ISSUE TITLE
Sudo powers

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#67]
It's very common to need `sudo` rights in scripts. We might consider a `SudoExec` method, for example, or perhaps just a `Sudo` filter which obtains `sudo` permissions, if possible, for all subsequent pipe operations.

**Comment by mainawycliffe** [comment]
Interesting idea, would love to have a crack at this.

**Comment by bitfield** [comment]
Go right ahead @mainawycliffe!

**Comment by mainawycliffe** [comment]
Excellent. I will look into it over the week and then we can discuss my idea on the implementation with what you have in mind.

**Comment by mainawycliffe** [comment]
after further play with the `gomarkdoc` tool, it's possible to generate the complete read me, but it will require moving the package intro section of the read me as a package comment, it works for the most part, but it's not compatible with markdown, but can be adopted to be somewhat decent.
