### ISSUE TITLE
Provide HTTP sink and source

### ISSUE THREAD

**Issue by hikhvar** [bitfield/script#73]
In todays scripting we often have to interact with HTTP APIs. Many APIs provide native Go SDKs, but there are lesser known APIs around without a proper SDK. We should provide a facility to provide similar HTTP capabilities to curl into the go scripting environment. Rolling a own HTTP client in go is not that hard, but it requires a lot of repetitive error checking. Today I wrote such a small script with `github.com/bitfield/script` and I missed build in HTTP capabilities alot.

I have seen https://github.com/bitfield/script/pull/3. This PR only implements a GET function. Interacting even with the simplest REST APIs requires us to use other methods like POST or PUT. Many APIs requires us to set custom headers. 

Therefore I propose the following sources:
```
// HTTPClient is an interface to allow the user to plugin alternative HTTP clients into the source.
// The HTTPClient interface is a subset of the methods provided by the http.Client
// We use an own interface with a minimal surface to allow make it easy to implement own customized clients.
// Customized clients are required to implement features like oauth2 or TLS client certificate authentication.
type HTTPClient interface {
	Do(r *http.Request) (*http.Response, error)
}

// HTTP executes the given http request with the default HTTP client from the http package. The response of that request,
// is processed by `process`. If process is nil, the default process function copies the body from the request to the pipe.
func HTTP(req *http.Request, process func(*http.Response) (io.Reader, error)) *Pipe {
	return HTTPWithClient(http.DefaultClient, req, process)
}

// HTTP executes the given http request with the given HTTPClient. The response of that request,
// is processed by `process`. If process is nil, the default process function copies the body from the request to the pipe.
func HTTPWithClient(client HTTPClient, req *http.Request, process func(*http.Response) (io.Reader, error)) *Pipe {
}
```
And the following sink:
```
// HTTPRequest creates a new HTTP request with the body set to the content of the pipe.
func (p *Pipe) HTTPRequest(method string, url string) (*http.Request, error) 
```
This allows us to simply post the content of files to remote URL like this:
```
func main() {
	req, err := script.Args().Concat().HTTPRequest(http.MethodPost, "https://httpbin.org/post")
	if err != nil {
		log.Fatal(err)
	}
	script.HTTP(req, nil).Stdout()
}
```
This is the equivalent of posting the contents of files via curl to a POST endpoint. 

I explored this design in the PR #72.
I'm open for feedback.

**Comment by bitfield** [comment]
Hey @hikhvar, thanks for the issue! This is a very interesting idea, and I'd definitely like to include some functionality like this.

However, one of the characteristics of good libraries (and, indeed, languages) is that they do a lot with a little. I'm not convinced, for example, that an `HTTPRequest` method which consists of a one-line call to `http.NewRequest` is really worth its inflationary effect on the API.

That doesn't mean it's a bad idea, just that I'd like us to try and tweak the design to be more powerful. If using `script` doesn't save you code, there's no point in using it. Could we come up with something which is more like (for example) using `curl` or `wget` in a shell script?

**Comment by hikhvar** [comment]
I'm fine with removing the `HTTPRequest`. I think `HTTP` and `HTTPWithClient` are the replacements for `wget` and `curl`. The first uses sane defaults to get a resource. The later offers the use the full flexibility offered by the golang stdlib http package.
Maybe remove the `process` mapping function from `HTTP`?
Like:
```
// HTTP executes the given http request with the default HTTP client from the http package. The response body of the request is copied to the Pipe
func HTTP(req *http.Request) (io.Reader, error)) *Pipe {
	return HTTPWithClient(http.DefaultClient, req, nil)
}
```

**Comment by bitfield** [comment]
A great way to explore and find the right design is to write example programs, I find. Could we construct a non-trivial example which uses HTTP requests in a pipeline in a realistic way? That will almost certainly tell us exactly what the API should look like.

**Comment by hikhvar** [comment]
I updated my DRAFT PR #72 with a rewrite of the HTTP API. I switched over to a fluent interface. The general idea is, that the `HTTP(url string)` function (the source) and method (the sink) on a `Pipe` creates a new `HTTPPipe`. This `HTTPPipe` can be configured with methods like `WithMethod` or `WithBody`. The HTTPPipe executes the HTTP request in a lazy fashion. The request is executed as soon as `Read()` or `Error()` of the HTTPPipe is called or the `AutoReadCloser` of the `Pipe` is read. Since the `HTTPPipe` is composed of a normal `Pipe`, every filter already defined can be used here. By default the source tries to fetch the provided URL with a `GET`. This is similar how tools like `curl` or `wget` work. 
The sink does by default a `POST`. This matches the behavior of `curl`. As soon as you provide data for the body, `curl` does a `POST` unless configured otherwise.

## Example Usecases:

### Download a file:

```go
func main() {
  script.HTTP("https://httpbin.org/json").WriteFile("download.json")
 }
```

### Download a file from a basic auth protected server:

```go
func basicAuth(username, password string) http.Header {

	auth := username + ":" + password
	enc := base64.StdEncoding.EncodeToString([]byte(auth))
	h := http.Header{}
	h.Set("Authorization", "Basic "+enc)
	return h
}

func main() {
	user, password := "admin", "supersecret"
	_, err := script.HTTP("https://httpbin.org/basic-auth/admin/supersecret").
		WithHeader(basicAuth(user, password)).
		WriteFile("download.txt")
	if err != nil {
		log.Fatal(err)
	}
}
```

### Post local JSON files to a URL. 
Example use cases from my day to day admin tasks are updating elasticsearch index templates.

```go
func main() {
	_, err := script.Args().
		MatchRegexp(regexp.MustCompile(".*\\.json")).
		First(1).
		Concat().
		HTTP("https://httpbin.org/put").
		WithHeader(http.Header{"Content-Type": []string{"application/json"}, "MyOrganisationsRequiredHeader": []string{"foo"}}).
		WithMethod(http.MethodPut).
		Stdout()
	if err != nil {
		log.Fatal(err)
	}
}
```

I think this interface gives us both, a simple interface for simple task but allows the user to construct complex HTTP requests required to talk to real REST APIs.

**Comment by bitfield** [comment]
This is neat, but I wish there weren't an `HTTPPipe` type. One of the nice things about `script` is that everything is a `Pipe`. Can we provide the same functionality using just `Pipe`?

**Comment by hikhvar** [comment]
I think we plump everything into the `Pipe`. However, what is the benefit of this? Sure, the library contains less types, but it does not help the user. What is the semantic of:
```
script.WithMethod("PUT").Match("bar").Stdout()
``` 
This will compile perfectly fine, but does not make any sense. Moreover it allows the user to write bugs like this:
```
_, err := script.Args().
		MatchRegexp(regexp.MustCompile(".*\\.json")).
		First(1).
		Concat().
		HTTP("https://httpbin.org/put").
		WithHeader(http.Header{"Content-Type": []string{"application/json"}, "MyOrganisationsRequiredHeader": []string{"foo"}}).
                Match("foo").
		WithMethod(http.MethodPut).
		Stdout()
```
In this case the `WithMethod()` call does not have any effect, but it will compile.

**Comment by bitfield** [comment]
Yes, that's not the answer. It's not just about what types exist in the program, but the fact that you don't want methods that are only meaningful for certain kinds of data.

What about something like this instead:

```go
script.HTTPGet("https://httpbin.org/json").Stdout()
...
req := http.NewRequest...
req.Header.Set...
script.HTTPDo(req)...
```

**Comment by hikhvar** [comment]
With this design the user can't:
* Access a REST Endpoint secured by client certificates. These have to be set in the underlying `http.Transport` of the `http.Client`.
* Access anything other than the response body. It gets really hard to check the response status code in a pipeline.
* Access the Headers of the response. 

Are that restrictions we are ok to live with? In those cases the user can fallback to a pure go implementation of the source and init the pipe with `script.NewPipe().WithReader(...)`.

If we choose this, we should document the limitations of our HTTPClient cleanly. 
I did not find any explicit API compatibility guarantees of the script library. Do we follow the default SemVer guarantees of only adding non-breaking API changes in a minor version?

**Comment by bitfield** [comment]
Well, as in any good API design, I aim to make simple things simple, and complicated things _possible_. What would it look like to set a custom HTTP client? Let's see if we can think of a reasonable way to do it which doesn't place an extra burden on someone who's happy with the default client (the `script` equivalent of `http.Get`, for example).

Similarly, how can we provide access to the response status and other headers?

> Do we follow the default SemVer guarantees of only adding non-breaking API changes in a minor version?

We are at `v0`, so breaking changes in minor versions are allowed and expected.

**Comment by hikhvar** [comment]
Whats your opinion on the following API combining your idea and my second idea with the HTTPPipe:
```
func HTTP(url string, httpOptions...) *Pipe
```
A normal GET looks like this:
```
script.HTTP("https://httpbin.org/json").Stdout()
```
When I want to modify the request, response or client I can use:
```
script.HTTP("https://httpbin.org/post", WithMethod("POST"), WithClient(c), WithResponseProcessor(f)).Stdout()
```

This has the following benefits:
* Users can modify all bells and  whistles of the HTTP request
* They must not modify anything other than the URL
* Everything is still a normal `Pipe`.

**Comment by bitfield** [comment]
Yes, functional options would be a nice pattern here (though a bit unwieldy as they'd have to be `script.WithMethod...` and so on).

Let's try and write non-trivial examples of both patterns (simple case, and extra configuration case), and see what API emerges.

**Comment by lalloni** [comment]
One alternative to functional options could be using a context.Context-available previously initialized http.Client, a pattern used on many other libraries and on the stdlib.

That made me think that having a Context to share state or resources and to control Pipe execution would make a lot of sense, only to find there is no support for it. This might be a good idea. 

How to add context.Context support might be a whole discussion but the simplest thing that comes to my mind is add a Context variant to all script Sources. A second alternative (although more complex) is to allow to set the context on a Pipe (on this alternative it would be complex to define and explain what happens when setting a Context on a Pipe that already has one). 

To play with this idea let's try the idea of having context variants for source methods:

```go
client := ... // initialize an http.Client with custom configuration
ctx := script.WithHTTPClient(context.Background(), client)
script.ExecContext(ctx,"find /").HTTPGet("https://example.com/service?filename={{.}}").WriteFile("/tmp/foo")
```

Please ignore the text/template-style argument to HTTPGet, it was just an idea popped out of my head while I was writing the example. I didn't think much about it but it could be a good idea.

Of course using a context could allow new features like having timeouts, cancellation, etc.

**Comment by bitfield** [comment]
This has been a very productive and helpful discussion, thank you. I'm still exploring ideas on this front, but let's close this and continue the good work over on #85, just to keep everything in one place.
