### ISSUE TITLE
Real-time output to stdout in a long-running command

### ISSUE THREAD

**Issue by besi1z** [bitfield/script#78]
e.g. for command like

```go
script.Exec("ping -c 100 www.google.com").Stdout()
```

I expect the result shows in stdout line by line just like real Bash script, instead of showing after the run.

Do you have tricks to get this done? or any plan/feature to implement this?

**Comment by bitfield** [comment]
That's a good suggestion! How do you envisage this looking from the code point of view? What `script` pipeline would you write to get real-time output?

**Comment by marco-m** [comment]
One possibility would be:
```go
script.Exec("ping -c 100 www.google.com").Stream()
```
and the implementation could just use StdoutPipe() and StderrPipe() of package os.exec, something along the lines of (didn't check the source of script.Exec, this code doesn't follow script's design with Pipe, it is just to give an idea):
```go
        cmd := exec.Command(...)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}

	if err := cmd.Start(); err != nil {
		return err
	}

	scanOut := bufio.NewScanner(stdout)
	for scanOut.Scan() {
		line := scanOut.Text()
		if line != "" {
			fmt.Println(line)
		}
	}
	scanErr := bufio.NewScanner(stderr)
	for scanErr.Scan() {
		line := scanErr.Text()
		if line != "" {
			fmt.Println(line)
		}
	}

        // maybe here we need something smarter and collect the errors so that we always call cmd.Wait()
	if err := scanOut.Err(); err != nil {
		return err
	}
	if err := scanErr.Err(); err != nil {
		return err
	}

	if err := cmd.Wait(); err != nil {
		return err
	}
```

**Comment by bitfield** [comment]
That sounds promising! Do you want to put a PR together along these lines so we can try it out?

**Comment by bitfield** [comment]
Now implemented in v0.19.0.

**Comment by madAndroid** [comment]
Has this actually been implemented? I see that the PR was closed and not merged, and I don't see anything in the docs around streaming of output.. is this still something that would be implemented in time? It would be really helpful to have a Go variant of something like Python's `subprocess`

**Comment by bitfield** [comment]
Yes, indeed. Here's what the [README](https://github.com/bitfield/script#filters) says:

> Note that filters run concurrently, rather than producing nothing until each stage has fully read its input. This is convenient for executing long-running comands, for example. If you do need to wait for the pipeline to complete, call `Wait`.

The canonical example is something like OP's:

```go
script.Exec("ping -c 100 www.google.com").Stdout()
```

But, as I say, *all* filters are now concurrent, including `Exec`. Try it!

**Comment by madAndroid** [comment]
Thank you for the reply - yes indeed, I can see the output is concurrent - I'm running a sonobuy test using `Exec()`, and the output is streamed to the console 👍

**Comment by bitfield** [comment]
Great! I look forward to seeing what interesting programs you come up with!
