### ISSUE TITLE
Comparison to Next Generation Shell

### ISSUE THREAD

**Issue by ilyash** [bitfield/script#82]
Hi!

I've translated some of the examples to Next Generation Shell.

If you think it's appropriate, you are welcome to add the following link somewhere:

https://github.com/ngs-lang/ngs/wiki/Code-Snippets-Comparisons#script-go-library

**Comment by bitfield** [comment]
Thanks @ilyash! That's most interesting. I hadn't heard of NGS before, but I read your examples with interest.

**Comment by ilyash** [comment]
Welcome @bitfield ,

Please let me know if you would like to have any further information (that also means that the documentation could be improved).

**Comment by bitfield** [comment]
No, I think you've covered it admirably! I might well follow your example at some point and add links to alternative shell-like languages such as NGS (but, to be honest, probably not).

**Comment by ilyash** [comment]
> links to alternative shell-like languages

If you decide to do that, I hope this link will save you a lot of effort:

https://github.com/oilshell/oil/wiki/Alternative-Shells
