### ISSUE TITLE
FEATURE: plug-in different Regex engines

### ISSUE THREAD

**Issue by ghost** [bitfield/script#83]
Thank you for publishing this useful tool @bitfield.

Would it be possible to add support for plugging different Regex engines in script? GoLang's **regexp** package does not support PCRE and without that there is no look-ahead nor look-behind functionality without which some problems cannot be solved. 

It would be great if script allowed for [1](https://github.com/gijsbers/go-pcre) or [2](https://github.com/dlclark/regexp2). Ideally both, otherwise maybe only [1](https://github.com/gijsbers/go-pcre) due to [superior performance](https://xrstf.de/2018/04/go-regexp-vs-pcre/).

**Comment by bitfield** [comment]
That's a very interesting idea @MagnifiGo! I guess you can use any regex engine you like right now using `EachLine`—does that solve your problem? If not, how would you envisage users being able to select different regex implementations in their `script` programs? Perhaps you could write an example showing how this might work, and we can chew it over.

**Comment by MagnifiGo** [comment]
@bitfield my goal is to perform match & replace in files and if memory serves `EachLine` merely collects lines containing a match in a string builder.

Regarding your second question, when time allows I will study the **script** implementation and see what can be done.
