### ISSUE TITLE
Errors not working the way I thought

### ISSUE THREAD

**Issue by rmasci** [bitfield/script#84]
So if I have a command that has an obvious error:
```
func main() {
	p := script.Exec("cat /etc/shels")
	Str, err := p.String()
	if err != nil {
		fmt.Println(Str, err)
	} else {
		fmt.Println(Str)
	}

}
```
I get the following output:
```
exit status 1
```
If I change the first line to:
```
p := script.Exec("cat /etc/shells")
```
I get the output from cat.

I looked at the code and when the exec it done it uses exec.CombinedOutput so I am wondering why I don't see the error from cat?

**Comment by bitfield** [comment]
The reason for this is explained in the section on [Error output](https://github.com/bitfield/script#error-output). An error in any stage of the pipe makes the rest of the pipe a no-op, including `String`. If you want to see the output from an `Exec` command that has failed, you need to explicitly reset the error status of the pipe:

```go
func main() {
	p := script.Exec("cat bogus")
	if p.Error() != nil {
		p.SetError(nil)
	}
	p.Stdout()
}
```

This produces the output you were expecting.

**Comment by rmasci** [comment]
I guess I missed that section on 'Error output' Sorry about that -- thanks for getting back to me, it works and simplifies a program that I am writing that allows for non-human Linux accounts with 'nologin' shells (Company policy) to be able to launch commands via ssh.

**Comment by hobti01** [comment]
Ah this tripped me up too.  The text "reset the error status of the pipe" could be clarified to say "reset the error status of the pipe with SetError(nil)"

BTW, thanks for the nice library!
