### ISSUE TITLE
Trim

### ISSUE THREAD

**Issue by hooksie1** [bitfield/script#98]
Just found this project today, it's really awesome! 

I started to work on a PR for a trim method that works like `tr -d`. I realize that Go has strings.Trim/strings.ReplaceAll (I actually used strings.ReplaceAll in the method) but it would be nice for those used to Unix systems to have similar named things to work with. Let me know if this is something wanted or not.

**Comment by bitfield** [comment]
Thanks @hooksie1! What kind of use case do you envisage for this? Maybe you could write a program that uses the Trim functionality as part of some kind of systems program. What would it do? That's always a nice way to think about the behaviour we need, and what API would make sense for it.

**Comment by hooksie1** [comment]
So I'm thinking in the past where I've had to pipe data into `tr` to trim off things like slashes, dashes, colons, etc. What I wrote takes in a string and treats it as a slice, loops through it, and removes the characters from the piped input. For example with the file contents:

`hey-what's/up`

the script `script.File("test.txt").Trim("-/'").Stdout()` outputs `heywhatsup`

**Comment by bitfield** [comment]
Great! So what kind of thing were you doing when you needed to trim these characters? It's always easier to make the case for a feature if you have a real systems program that needs it.

**Comment by hooksie1** [comment]
One big one that stands out in my mind is trimming new lines from data that needs to be base64 encoded. Another is receiving JSON data from something that has `\"` around the keys and values. So we've had to trim the backslashes from the payload.

**Comment by bitfield** [comment]
Nice! Okay, let's try to write one of those programs. You can use `EachLine` to do the trimming for now—then we can look at the result and see if a `Trim` method would really earn its place in the API.

**Comment by hooksie1** [comment]
Yeah that's exactly what I did. I had a PR set up but then noticed the contributing guide so I opened this first. Here's what I have:

```
// Trim takes in a string of characters to trim and removes them from
// the contents of the Pipe. Similar to how tr -d works.
func (p *Pipe) Trim(s string) *Pipe {
	return p.EachLine(func(line string, out *strings.Builder) {
		data := []rune(line)
		match := []rune(s)
		if s != "" {
			for _, v := range match {
				for j := 0; j < len(data); j++ {
					if v == data[j] {
						data = append(data[:j], data[j+1:]...)
					}
				}
			}
		}
		out.WriteString(string(data))
		out.WriteRune('\n')
	})
}
```

I figured a new Method would lend well since sometimes slice work can be annoying if you just want to write a quick script.

**Comment by bitfield** [comment]
So can you write a useful systems program that uses your method?

**Comment by bitfield** [comment]
Closing for now, but let's reopen this once we have a real-world program demonstrating the need for the feature.
